version: '2'

services:
  app:
    image: jeron1mo/nodejs-api-kub
    container_name: nodejs-api
    restart: always
    env_file: .env
    ports:
      - '$PORT:$PORT'
    links:
      - $DB_HOST

  mongo:
    image: mongo:latest
    container_name: $DB_HOST
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=$DB_NAME
    ports:
      - '$DB_PORT:$DB_PORT'

volumes:
  dbdata:
