apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\dzmitry.sakhvon\Desktop\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\dzmitry.sakhvon\Desktop\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
      - env:
        - name: CORS_URL
          value: '*'
        - name: DB_HOST
          value: mongo12
        - name: DB_NAME
          value: posts
        - name: DB_PORT
          value: "27017"
        - name: GOOGLE_CLIENT_ID
          valueFrom: 
            secretKeyRef:
              key: GOOGLE_CLIENT_ID
              name: app-secret
        - name: GOOGLE_CLIENT_SECRET
          valueFrom: 
            secretKeyRef:
              key: GOOGLE_CLIENT_SECRET
              name: app-secret
        - name: MONGO_INITDB_DATABASE
          value: posts
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "5000"
        image: mongo:latest
        imagePullPolicy: ""
        name: mongo12
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
