apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  GOOGLE_CLIENT_ID: MTAwOTE0NTg2ODQzMy1zZGIxczEzYWRma242Z2tuZzFpYWRnNG03Z3JxajR0dC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQ==
  GOOGLE_CLIENT_SECRET: RTBNT0xwdUR5Tk1hQm9NNnNSelplc01l
