apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\dzmitry.sakhvon\Desktop\kompose.exe convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  type: LoadBalancer
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
